# v: bsh-smp-01
"""Realistic sample article data (stands in for live RSS while sandbox can't fetch).
Shape matches sources.fetch_all() output exactly."""
from datetime import datetime, timezone
def _d(s): return datetime.fromisoformat(s).replace(tzinfo=timezone.utc)

SAMPLE = [
    {"title":"Federal Reserve holds rates steady as inflation signals stay mixed","summary":"The US central bank kept its benchmark rate unchanged, citing uncertainty over price pressures and a cooling labour market.","link":"http://x/1","published":_d("2026-06-26T08:00:00"),"source":"CNBC Intl","region":"global","category":"business","source_type":"markets"},
    {"title":"China tightens export controls on rare earth processing technology","summary":"New restrictions target the technology used to refine rare earths, escalating the resource standoff with Western economies.","link":"http://x/2","published":_d("2026-06-26T06:30:00"),"source":"SCMP","region":"asia","category":"world","source_type":"newspaper"},
    {"title":"EU finalises landmark AI regulation after months of talks","summary":"The bloc agreed comprehensive rules governing high-risk AI systems, setting a global benchmark for oversight.","link":"http://x/3","published":_d("2026-06-26T07:15:00"),"source":"Deutsche Welle","region":"europe","category":"world","source_type":"public"},
    {"title":"Japanese firm announces solid-state battery production breakthrough","summary":"Engineers report a manufacturing method that could make solid-state batteries viable at scale, a key step for electric vehicles.","link":"http://x/4","published":_d("2026-06-26T05:00:00"),"source":"Japan Times","region":"asia","category":"world","source_type":"newspaper"},
    {"title":"Red Sea tensions push global shipping rates sharply higher","summary":"Freight costs spiked as carriers reroute around the region, adding pressure to supply chains and prices.","link":"http://x/5","published":_d("2026-06-26T04:00:00"),"source":"MarketWatch","region":"global","category":"business","source_type":"markets"},
    {"title":"New open-weight language model rivals closed competitors on benchmarks","summary":"A major lab released model weights openly, posting scores competitive with leading proprietary systems.","link":"http://x/6","published":_d("2026-06-26T09:00:00"),"source":"Ars Technica","region":"global","category":"tech","source_type":"analysis"},
    {"title":"Drought conditions worsen across southern Europe ahead of summer","summary":"Reservoir levels fall to multi-year lows, threatening agriculture and water supplies in several countries.","link":"http://x/7","published":_d("2026-06-26T03:30:00"),"source":"RFI English","region":"europe-africa","category":"world","source_type":"public-radio"},
    {"title":"India unveils expanded semiconductor manufacturing incentives","summary":"The government announced fresh subsidies aimed at attracting chip fabrication plants and reducing import dependence.","link":"http://x/8","published":_d("2026-06-26T02:00:00"),"source":"Times of India","region":"asia","category":"world","source_type":"newspaper"},
    {"title":"Study finds new mechanism in how the brain consolidates memory","summary":"Researchers identified a signalling pathway active during sleep that appears central to forming long-term memories.","link":"http://x/9","published":_d("2026-06-26T01:00:00"),"source":"ScienceDaily","region":"global","category":"science","source_type":"research"},
    {"title":"Streaming giant restructures as subscriber growth slows","summary":"The company announced layoffs and a strategy shift toward live content amid a maturing market.","link":"http://x/10","published":_d("2026-06-25T22:00:00"),"source":"The Verge","region":"global","category":"tech","source_type":"product-news"},
    {"title":"Singapore unveils framework for cross-border data flows","summary":"The city-state set out rules intended to ease data movement for financial firms across Asian markets.","link":"http://x/11","published":_d("2026-06-26T03:10:00"),"source":"Straits Times","region":"asia","category":"world","source_type":"newspaper"},
    {"title":"African leaders meet on regional trade integration","summary":"Heads of state gathered to push a continental free-trade agenda, targeting tariff reductions and infrastructure links.","link":"http://x/12","published":_d("2026-06-26T01:40:00"),"source":"RFI English","region":"europe-africa","category":"world","source_type":"public-radio"},
    {"title":"Researchers report progress on room-temperature superconductor","summary":"A team published data on a material showing reduced resistance at higher temperatures, though independent replication is pending.","link":"http://x/13","published":_d("2026-06-26T00:30:00"),"source":"ScienceDaily","region":"global","category":"science","source_type":"research"},
    {"title":"Major cloud provider reports widespread outage","summary":"Services were disrupted for hours across several regions before being restored; the cause is under investigation.","link":"http://x/14","published":_d("2026-06-26T10:30:00"),"source":"Ars Technica","region":"global","category":"tech","source_type":"analysis"},
    {"title":"German manufacturing orders fall for a third month","summary":"New factory orders declined again, deepening concerns about the euro-area industrial outlook.","link":"http://x/15","published":_d("2026-06-26T07:50:00"),"source":"Deutsche Welle","region":"europe","category":"business","source_type":"public"},
    {"title":"Hong Kong tightens listing rules for tech firms","summary":"The exchange introduced stricter disclosure requirements aimed at improving investor protection.","link":"http://x/16","published":_d("2026-06-26T05:20:00"),"source":"SCMP","region":"asia","category":"business","source_type":"newspaper"},
    {"title":"New telescope survey maps thousands of distant galaxies","summary":"Astronomers released an early catalogue from a wide-field survey, offering fresh data on cosmic structure.","link":"http://x/17","published":_d("2026-06-25T20:00:00"),"source":"MIT Tech Review","region":"global","category":"science","source_type":"analysis-deep"},
    {"title":"US lawmakers advance bill on chip supply resilience","summary":"A bipartisan measure would expand incentives for domestic semiconductor production and stockpiling.","link":"http://x/18","published":_d("2026-06-26T09:30:00"),"source":"NPR World","region":"us","category":"world","source_type":"public-radio"},
]
